- name: Workday enter time
  hosts: localhost
  vars_files: credentials.yml
  vars:
    - rh_username: "{{ username | default('') }}"
    - rh_password: "{{ password | default('') }}"
    - counter: 0
    - status: "Away"

  tasks:
    - name: Generate selenium script
      template:
        src: workday.py.j2
        dest: "/tmp/workday.py"
